# Generated by Django 5.2.1 on 2025-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.CharField(max_length=100, unique=True, verbose_name='ID de la Orden')),
                ('sesion_id', models.CharField(max_length=100, verbose_name='ID de Sesión')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
