# Generated by Django 5.2.1 on 2025-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0002_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='codigo_fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='codigo_interno',
            field=models.CharField(default='GEN-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
