# Generated by Django 5.2.1 on 2025-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0003_herramienta_codigo_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='codigo_interno',
            field=models.CharField(default='FER-0000', max_length=50),
        ),
    ]
