# Generated by Django 5.2.1 on 2025-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0004_alter_herramienta_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='codigo_interno',
            field=models.CharField(max_length=50),
        ),
    ]
