# Generated by Django 5.2.1 on 2025-05-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0005_alter_herramienta_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='categoria',
            field=models.CharField(choices=[('electricas', 'Eléctricas'), ('manuales', 'Manuales'), ('medicion', 'Medición'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
