# Generated by Django 5.0.6 on 2025-05-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0009_itemorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOrden',
        ),
    ]
