# Generated by Django 5.0.6 on 2025-05-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0011_serviciocliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioCliente',
        ),
    ]
