# Generated by Django 5.2.1 on 2025-07-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0013_mensajecontacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RespuestaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mensaje_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ferremas.mensajecontacto')),
            ],
        ),
    ]
