# Generated by Django 5.2.1 on 2025-07-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0014_mensajecontacto_respondido_respuestamensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='respondido',
        ),
    ]
