# Generated by Django 5.0.6 on 2025-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0015_remove_mensajecontacto_respondido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='tipo',
            field=models.CharField(choices=[('duda', 'Duda'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia')], default='duda', max_length=20),
        ),
    ]
