# Generated by Django 5.0.6 on 2025-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0016_mensajecontacto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
